# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'  # Generate a unique tag for each build

stages:
- stage: Build
  displayName: Build and Deploy
  jobs:
  - job: Build
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
      name: app-cicd
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'dockerhub registry'  # Your Docker Hub/Azure Container Registry connection
        repository: 'sazalach/app-cicd'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'  # Use Build ID as image tag

    - script: |
        echo "Before Update:"
        cat nodeapp.yaml  # Show the file before modification

        echo "Updating Kubernetes YAML file with new image tag"
        sed -i 's|image: sazalach/app-cicd:.*|image: sazalach/app-cicd:$(tag)|g' nodeapp.yaml

        echo "After Update:"
        cat nodeapp.yaml  # Show the file after modification

        # Ensure the updated file is applied
        kubectl apply -f nodeapp.yaml -n default
      displayName: Debug & Deploy to AKS





