# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
      name: app-cicd
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub registry'
        repository: 'sazalach/app-cicd'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh-webserver'
        runOptions: 'inline'
        inline: |
          docker login -u "sazalach" -p "$(docker_pat)"
                  docker pull sazalach/app-cicd:$(Build.BuildId)
                  docker run -d -p 8080:80 --name my-app sazalach/app-cicd:$(Build.BuildId)
        readyTimeout: '20000'
    
