# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and Deploy
  jobs:
  - job: Build
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
      name: app-cicd
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'dockerhub registry'  # Your Docker Hub/Azure Container Registry connection
        repository: 'sazalach/app-cicd'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    - task: trivy@1
      inputs:
        version: 'latest'
        image: 'docker.io/sazalach/app-cicd:latest'
        jsonOutput: true
        severities: 'CRITICAL'

    - task: Kubernetes@1
      displayName: Deploy to AKS
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-connect'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'nodeapp.yaml'




